### ISSUE TITLE
Proposal to move away from hidden burger menu to top menu

### ISSUE THREAD

**Issue by destos** [tulsawebdevs/twd-website#1]
I feel if we use a hamburger menu for all navigation we'll be missing interaction and dicovery opportunities for those looking to find more information about TWD.

More reading:
https://lmjabreu.com/post/why-and-how-to-avoid-hamburger-menus/
http://deep.design/the-hamburger-menu/

**Comment by nearbycoder** [comment]
Oh I read that article as well a few months back. Very good point. I'm not against top nav menus. Mobile wise it can end up being a mess depending on the nav structure. Drop downs are a way to get around this but again on mobile it leaves a bad taste. Do we have a nav structure that we know we would like to use? I think knowing that would leave a better understanding of what we could use.

**Comment by nearbycoder** [comment]
On a plus side it removes the only third party dependency thus far.

**Comment by destos** [comment]
In new layout html we've added a header menu
