### ISSUE TITLE
Custom Sass Grid Layout

### ISSUE THREAD

**Issue by nearbycoder** [tulsawebdevs/twd-website#2]
Just to keep everyone informed on how the scss works I am opening this issue. I will be creating documentation for the scss grid layout in the coming days to make it easier for new users to use.

As well I am not against switching to a framework if we decide to go that way. My main reasoning for creating this was *why bloat the stack when we can just go for simplicity*. Yes, I understand that there are many other small css grid libraries that we could use as well. 

> Of course why rebuild the wheel if it already exists is another opinion that could be said.

My thoughts on this is that if we build something from the ground up we can all have a say in how it is defined. As well it can be easily integrated into additional twd projects. I look forward to hearing opinions and/or thoughts on this. Additional info will be posted later this week.

**Comment by destos** [comment]
My confusion is why name what appears to be column a row.
Rows should encapsulate a column, but that may be from my familiarity with bootstrap.
Also keeping to symantic CSS naming conventions would be preferrable. At the moment you have a short class for the container `c` which isn't very helpful when reading the html.

**Comment by nearbycoder** [comment]
Actually that needs to be abstracted to another class. Really he reuse of the c or short container name was to add the flex property onto the element. Great catch and will fix when I go back through it. As for the short class name it was to try and keep the class attribute down in size and can be configured in the variables or just dropped. For instance r-md-6 can be easy changed to row-md-6 as well through a variable assignment. I really do appreciate the feedback it's nice to actually have someone look over my code.

**Comment by nearbycoder** [comment]
Updated repo to reflect a more bootstrap look and feel. Removed short container name alias for symantic CSS naming conventions.

**Comment by destos** [comment]
We've moved to use semanti-ui and it's grid system
