### ISSUE TITLE
Confusion with install/build process

### ISSUE THREAD

**Issue by nearbycoder** [tulsawebdevs/twd-website#3]
The whole **./script/install** & **./script/dev** is throwing me off a bit. I understand how it works but why not just do **npm instal**l and **npm run dev** in the root directory. Seems shorter and easier to work with? Is this to help people who don't understand npm and gulp into the workflow?

**Comment by destos** [comment]
It's semi following this pattern:
http://githubengineering.com/scripts-to-rule-them-all/
https://github.com/github/scripts-to-rule-them-all

**Comment by nearbycoder** [comment]
Okay that makes sense. going ahead and closing the issue.
